import { PrismaClient, VetLabType } from "@prisma/client";

export const VET_LAB_SEED_RECORDS = [
  {
    id: "vet-gadvasu-ludhiana",
    name: "Dr. Harpreet Singh Gill, MVSc (Poultry Medicine)",
    type: VetLabType.VET,
    qualification: "MVSc Avian Medicine (GADVASU), PhD Poultry Pathology",
    verified: true,
    phone: "+919876543210",
    whatsapp: "+919876543210",
    address: "GADVASU Poultry Clinical Wing, Ferozepur Road, Ludhiana, Punjab 141004",
    latitude: 30.9022,
    longitude: 75.808,
    serviceRadiusKm: 80,
    specializations: [
      "Broiler Respiratory Diseases",
      "Newcastle / IB Diagnosis",
      "Post-Mortem Autopsy",
      "Biosecurity Audits",
    ],
    languages: ["Punjabi", "English", "Hindi"],
    teleconsult: true,
    hours: "Mon-Sat: 08:00 - 17:00",
  },
  {
    id: "lab-nrddl-ludhiana",
    name: "Northern Regional Disease Diagnostic Laboratory (NRDDL)",
    type: VetLabType.LAB,
    qualification: "ICAR/DAHD Accredited Regional Diagnostic Reference Lab",
    verified: true,
    phone: "+911612401960",
    whatsapp: "+919872201960",
    address: "NRDDL Complex, PAU Campus, Ludhiana, Punjab 141004",
    latitude: 30.901,
    longitude: 75.8573,
    serviceRadiusKm: 150,
    specializations: [
      "Avian Influenza PCR",
      "Serological Titres (HI/ELISA)",
      "Feed Mycotoxin Screening",
      "Bacterial Culture & Sensitivity",
    ],
    languages: ["Punjabi", "English", "Hindi"],
    teleconsult: false,
    hours: "Mon-Fri: 09:00 - 16:30",
  },
  {
    id: "assoc-ppfa-ludhiana",
    name: "Punjab Poultry Farmers Association (PPFA) Helpline",
    type: VetLabType.ASSOCIATION,
    qualification: "Apex State Poultry Cooperative Federation",
    verified: true,
    phone: "+911612503411",
    whatsapp: "+919888123456",
    address: "Kisan Vikas Chamber, Phase 2, Urban Estate, Ludhiana, Punjab 141002",
    latitude: 30.895,
    longitude: 75.845,
    serviceRadiusKm: 250,
    specializations: [
      "Emergency Farm Crisis Escalation",
      "Bulk Feed Quality Advisory",
      "Disease Outbreak Early Warning Network",
    ],
    languages: ["Punjabi", "Hindi"],
    teleconsult: true,
    hours: "24x7 Farmer Helpline",
  },
  {
    id: "vet-majha-amritsar",
    name: "Dr. Manmohan Singh Randhawa, B.V.Sc & A.H",
    type: VetLabType.VET,
    qualification: "B.V.Sc & A.H, PGD Commercial Poultry Management",
    verified: true,
    phone: "+919814123456",
    whatsapp: "+919814123456",
    address: "Majha Poultry Healthcare Center, Court Road, Amritsar, Punjab 143001",
    latitude: 31.634,
    longitude: 74.8723,
    serviceRadiusKm: 65,
    specializations: [
      "Layer Egg-Drop Syndrome",
      "Broiler Gut Health & Coccidiosis",
      "Vaccination Schedule Audits",
    ],
    languages: ["Punjabi", "Hindi", "English"],
    teleconsult: true,
    hours: "Mon-Sat: 09:00 - 18:00",
  },
  {
    id: "lab-amritsar-pathology",
    name: "Amritsar Avian Pathology & Feed Testing Lab",
    type: VetLabType.LAB,
    qualification: "NABL Accredited Veterinary Diagnostics",
    verified: true,
    phone: "+911832567890",
    whatsapp: "+919814098765",
    address: "GT Road Near Khalsa College, Amritsar, Punjab 143002",
    latitude: 31.625,
    longitude: 74.885,
    serviceRadiusKm: 70,
    specializations: [
      "Drinking Water Potability (TDS/Coliform)",
      "Feed Proximate Analysis",
      "Fecal Oocyst Floats",
    ],
    languages: ["Punjabi", "English"],
    teleconsult: false,
    hours: "Mon-Sat: 08:30 - 16:00",
  },
  {
    id: "vet-doaba-jalandhar",
    name: "Dr. Gurinder Singh Dhillon, MVSc",
    type: VetLabType.VET,
    qualification: "MVSc Veterinary Preventive Medicine",
    verified: true,
    phone: "+919878012345",
    whatsapp: "+919878012345",
    address: "Doaba Poultry Advisory Clinic, Civil Lines, Jalandhar, Punjab 144001",
    latitude: 31.326,
    longitude: 75.5762,
    serviceRadiusKm: 65,
    specializations: [
      "Colibacillosis & E. coli Control",
      "Hatchery Sanitation",
      "Flock Necropsy Evaluation",
    ],
    languages: ["Punjabi", "Hindi", "English"],
    teleconsult: true,
    hours: "Mon-Sat: 09:00 - 17:30",
  },
  {
    id: "lab-jalandhar-micro",
    name: "Jalandhar Avian Microbiological & Serology Lab",
    type: VetLabType.LAB,
    qualification: "State Department of Animal Husbandry Referral Unit",
    verified: true,
    phone: "+911812233445",
    whatsapp: "+919878954321",
    address: "Veterinary Polyclinic Complex, BMC Chowk, Jalandhar, Punjab 144001",
    latitude: 31.318,
    longitude: 75.589,
    serviceRadiusKm: 85,
    specializations: [
      "Antibiotic Sensitivity Testing (AST)",
      "Salmonella Isolation",
      "Serum HI Titres",
    ],
    languages: ["Punjabi", "English", "Hindi"],
    teleconsult: false,
    hours: "Mon-Fri: 09:00 - 17:00",
  },
  {
    id: "vet-malwa-bathinda",
    name: "Dr. Jaswinder Kaur Virk, MVSc",
    type: VetLabType.VET,
    qualification: "MVSc Avian Pathology, Certified Farm Biosecurity Auditor",
    verified: true,
    phone: "+919417012345",
    whatsapp: "+919417012345",
    address: "Malwa Broiler & Layer Care Clinic, Bibiwala Road, Bathinda, Punjab 151001",
    latitude: 30.211,
    longitude: 74.9455,
    serviceRadiusKm: 60,
    specializations: [
      "Summer Heat-Stress Mitigation",
      "Infectious Bursal Disease (Gumboro)",
      "Nutritional Deficiencies",
    ],
    languages: ["Punjabi", "English", "Hindi"],
    teleconsult: true,
    hours: "Mon-Sat: 08:30 - 18:00",
  },
  {
    id: "lab-bathinda-postmortem",
    name: "Bathinda Animal Health & Post-Mortem Center",
    type: VetLabType.LAB,
    qualification: "District Veterinary Referral Hospital Lab",
    verified: true,
    phone: "+911642211998",
    whatsapp: "+919417898765",
    address: "Near Rose Garden, Goniana Road, Bathinda, Punjab 151002",
    latitude: 30.218,
    longitude: 74.952,
    serviceRadiusKm: 75,
    specializations: [
      "On-Site Post-Mortem Autopsy",
      "Parasitology (Coccidia/Worms)",
      "Water Mineral & Hardness Profile",
    ],
    languages: ["Punjabi", "Hindi"],
    teleconsult: false,
    hours: "Mon-Sat: 09:00 - 16:00",
  },
  {
    id: "vet-patiala-sandhu",
    name: "Dr. Amandeep Singh Sandhu, MVSc",
    type: VetLabType.VET,
    qualification: "MVSc Veterinary Epidemiology & Preventive Medicine",
    verified: true,
    phone: "+919815012345",
    whatsapp: "+919815012345",
    address: "Patiala Avian Clinical Consultancy, Lehal Colony, Patiala, Punjab 147001",
    latitude: 30.3398,
    longitude: 76.3869,
    serviceRadiusKm: 55,
    specializations: [
      "Chronic Respiratory Disease (CRD)",
      "Layer Cage Fatigue",
      "Flock Medication Management",
    ],
    languages: ["Punjabi", "Hindi", "English"],
    teleconsult: true,
    hours: "Mon-Sat: 09:00 - 18:30",
  },
  {
    id: "lab-patiala-serology",
    name: "Patiala Avian Diagnostic & Serology Centre",
    type: VetLabType.LAB,
    qualification: "Specialized Poultry Laboratory Group",
    verified: true,
    phone: "+911752345678",
    whatsapp: "+919815987654",
    address: "Rajpura Road Near Urban Estate, Patiala, Punjab 147002",
    latitude: 30.345,
    longitude: 76.392,
    serviceRadiusKm: 70,
    specializations: [
      "NDV/IBDV Antibody Titre Assays",
      "Feed Moisture & Fungal Toxin Counts",
      "Bacterial Isolation",
    ],
    languages: ["Punjabi", "English"],
    teleconsult: false,
    hours: "Mon-Sat: 09:00 - 17:00",
  },
  {
    id: "vet-moga-brar",
    name: "Dr. Kuldeep Singh Brar, B.V.Sc & A.H",
    type: VetLabType.VET,
    qualification: "B.V.Sc & A.H, 18 Years Commercial Poultry Experience",
    verified: true,
    phone: "+919888012345",
    whatsapp: "+919888012345",
    address: "Brar Poultry Advisory Clinic, Baghapurana Road, Moga, Punjab 142001",
    latitude: 30.8165,
    longitude: 75.1717,
    serviceRadiusKm: 50,
    specializations: [
      "Commercial Broiler Health",
      "Ventilation Failure Emergency",
      "Cannibalism & Feather Pecking",
    ],
    languages: ["Punjabi", "Hindi"],
    teleconsult: true,
    hours: "Mon-Sat: 08:00 - 19:00",
  },
  {
    id: "vet-sangrur-dhillon",
    name: "Dr. Baljit Singh Dhillon, MVSc",
    type: VetLabType.VET,
    qualification: "MVSc Avian Pathology",
    verified: true,
    phone: "+919872012345",
    whatsapp: "+919872012345",
    address: "Sangrur Avian Healthcare Hub, Dhuri Road, Sangrur, Punjab 148001",
    latitude: 30.2458,
    longitude: 75.8421,
    serviceRadiusKm: 60,
    specializations: [
      "Infectious Coryza",
      "Broiler Ascites & Sudden Death",
      "Biosecurity Planning",
    ],
    languages: ["Punjabi", "English", "Hindi"],
    teleconsult: true,
    hours: "Mon-Sat: 09:00 - 18:00",
  },
  {
    id: "vet-fatehgarh-sahib",
    name: "Dr. Prabhjot Kaur Grewal, MVSc",
    type: VetLabType.VET,
    qualification: "MVSc Veterinary Medicine, Ex-Veterinary Officer",
    verified: true,
    phone: "+919814512345",
    whatsapp: "+919814512345",
    address: "Sirhind-Fatehgarh Sahib Poultry Clinic, GT Road, Sirhind, Punjab 140406",
    latitude: 30.6425,
    longitude: 76.388,
    serviceRadiusKm: 55,
    specializations: [
      "Broiler Chick Quality Assessment",
      "Enteric Disorders",
      "Brooding Stress Recovery",
    ],
    languages: ["Punjabi", "English", "Hindi"],
    teleconsult: true,
    hours: "Mon-Sat: 08:30 - 17:30",
  },
];

export async function seedVetLabs(prismaClient?: PrismaClient) {
  const db = prismaClient || new PrismaClient();
  console.log(`🏥 Seeding ${VET_LAB_SEED_RECORDS.length} verified Punjab Vets, Labs & Associations...`);

  for (const record of VET_LAB_SEED_RECORDS) {
    await db.vetLab.upsert({
      where: { id: record.id },
      update: {
        name: record.name,
        type: record.type,
        qualification: record.qualification,
        verified: record.verified,
        phone: record.phone,
        whatsapp: record.whatsapp,
        address: record.address,
        latitude: record.latitude,
        longitude: record.longitude,
        serviceRadiusKm: record.serviceRadiusKm,
        specializations: record.specializations,
        languages: record.languages,
        teleconsult: record.teleconsult,
        hours: record.hours,
      },
      create: record,
    });
  }

  console.log(`✅ Successfully seeded ${VET_LAB_SEED_RECORDS.length} VetLab records.`);
}

if (require.main === module) {
  const prisma = new PrismaClient();
  seedVetLabs(prisma)
    .catch((err) => {
      console.error("❌ Error seeding VetLab records:", err);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
